### ISSUE TITLE
Play Backend

### ISSUE THREAD

**Issue by CiviledCode** [CiviledCode/goctf#1]
# TODO
- [x] Redirect to /join for re-authentication if room_code or token is invalid.
- [x] Redirect to /team if user team is nil.
- [x] Create /game websocket and push question data on there when requested or when there's an update.
- [x] Poll data to all users connected to webhook that apply under a criteria (typically their team).
- [x] Load HTML template and serve accordingly.
